CLASS all_primitives
    VAR PUBLIC
        myBOOL	        :       BOOL	      ;
        myBYTE	        :       BYTE	      ;
        myWORD	        :       WORD	      ;
        myDWORD	        :       DWORD	      ;
        myLWORD	        :       LWORD	      ;
        mySINT	        :       SINT	      ;
        myINT	        :       INT	          ;
        myDINT	        :       DINT	      ;
        myLINT	        :       LINT	      ;
        myUSINT	        :       USINT	      ;
        myUINT	        :       UINT	      ;
        myUDINT	        :       UDINT	      ;
        myULINT	        :       ULINT	      ;
        myREAL	        :       REAL	      ;
        myLREAL	        :       LREAL	      ;
        myTIME	        :       TIME	      ;
        myLTIME	        :       LTIME	      ;
        myDATE	        :       DATE	      ;
     //   myLDATE	        :       LDATE	      ;
        myTIME_OF_DAY	:       TIME_OF_DAY	  ;
     //   myLTIME_OF_DAY	:       LTIME_OF_DAY  ;
        myDATE_AND_TIME  :      DATE_AND_TIME ;
     //   myLDATE_AND_TIME :      LDATE_AND_TIME;
     //   myCHAR	        :       CHAR	      ;
     //   myWCHAR	        :       WCHAR	      ;
        mySTRING	        :   STRING	      ;
        myWSTRING	    :       WSTRING	      ;


       

    END_VAR
    
    METHOD PUBLIC Start : INT
        VAR_INPUT
            value : INT;
            value2 : INT;
        END_VAR

        myINT := value;
    END_METHOD

    METHOD PUBLIC Stop
        ;
    END_METHOD
END_CLASS