//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ix_integration_plc.ResourcesOverrride {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OverridePlcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverridePlcStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ix_integration_plc.ResourcesOverrride.OverridePlcStringResources", typeof(OverridePlcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOL From PLC.
        /// </summary>
        public static string BOOL_From_PLC {
            get {
                return ResourceManager.GetString("BOOL_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYTE From PLC.
        /// </summary>
        public static string BYTE_From_PLC {
            get {
                return ResourceManager.GetString("BYTE_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE From PLC.
        /// </summary>
        public static string DATE_From_PLC {
            get {
                return ResourceManager.GetString("DATE_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_AND_TIME From PLC.
        /// </summary>
        public static string DATE_UNDERSCORE_AND_UNDERSCORE_TIME_From_PLC {
            get {
                return ResourceManager.GetString("DATE_UNDERSCORE_AND_UNDERSCORE_TIME_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENUM Station status.
        /// </summary>
        public static string ENUM_Station_status {
            get {
                return ResourceManager.GetString("ENUM_Station_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer From PLC.
        /// </summary>
        public static string Integer_From_PLC {
            get {
                return ResourceManager.GetString("Integer_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LREAL From PLC.
        /// </summary>
        public static string LREAL_From_PLC {
            get {
                return ResourceManager.GetString("LREAL_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL From PLC.
        /// </summary>
        public static string REAL_From_PLC {
            get {
                return ResourceManager.GetString("REAL_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRING From PLC.
        /// </summary>
        public static string STRING_From_PLC {
            get {
                return ResourceManager.GetString("STRING_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME_OF_DAY From PLC.
        /// </summary>
        public static string TIME_UNDERSCORE_OF_UNDERSCORE_DAY_From_PLC {
            get {
                return ResourceManager.GetString("TIME_UNDERSCORE_OF_UNDERSCORE_DAY_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInteger From PLC.
        /// </summary>
        public static string UInteger_From_PLC {
            get {
                return ResourceManager.GetString("UInteger_From_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD From PLC.
        /// </summary>
        public static string WORD_From_PLC {
            get {
                return ResourceManager.GetString("WORD_From_PLC", resourceCulture);
            }
        }
    }
}
