//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXSharp.RenderableContent.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXSharp.RenderableContent.Tests.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOL From PLC.
        /// </summary>
        internal static string ___BOOL_From_PLC__ {
            get {
                return ResourceManager.GetString("___BOOL_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOL unknown From PLC.
        /// </summary>
        internal static string ___BOOL_unknown_From_PLC__ {
            get {
                return ResourceManager.GetString("___BOOL_unknown_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYTE From PLC.
        /// </summary>
        internal static string ___BYTE_From_PLC__ {
            get {
                return ResourceManager.GetString("___BYTE_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Instance.
        /// </summary>
        internal static string ___Complex_Instance__ {
            get {
                return ResourceManager.GetString("___Complex_Instance__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_AND_TIME From PLC.
        /// </summary>
        internal static string ___DATE_AND_TIME_From_PLC__ {
            get {
                return ResourceManager.GetString("___DATE_AND_TIME_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE From PLC.
        /// </summary>
        internal static string ___DATE_From_PLC__ {
            get {
                return ResourceManager.GetString("___DATE_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE unknown From PLC.
        /// </summary>
        internal static string ___DATE_unknown_From_PLC__ {
            get {
                return ResourceManager.GetString("___DATE_unknown_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew Point.
        /// </summary>
        internal static string ___Dew_Point__ {
            get {
                return ResourceManager.GetString("___Dew_Point__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string ___Hello__ {
            get {
                return ResourceManager.GetString("___Hello__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer From PLC.
        /// </summary>
        internal static string ___Integer_From_PLC__ {
            get {
                return ResourceManager.GetString("___Integer_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer unknown From PLC.
        /// </summary>
        internal static string ___Integer_unknown_From_PLC__ {
            get {
                return ResourceManager.GetString("___Integer_unknown_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is as cold as it should be at the nort pole..
        /// </summary>
        internal static string ___It_is_as_cold_as_it_should_be_at_the_nort_pole___ {
            get {
                return ResourceManager.GetString("___It_is_as_cold_as_it_should_be_at_the_nort_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is as cold as it should be at the souht pole..
        /// </summary>
        internal static string ___It_is_as_cold_as_it_should_be_at_the_souht_pole___ {
            get {
                return ResourceManager.GetString("___It_is_as_cold_as_it_should_be_at_the_souht_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fairly warm at the north pole..
        /// </summary>
        internal static string ___It_is_fairly_warm_at_the_north_pole___ {
            get {
                return ResourceManager.GetString("___It_is_fairly_warm_at_the_north_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fairly warm at the south pole..
        /// </summary>
        internal static string ___It_is_fairly_warm_at_the_south_pole___ {
            get {
                return ResourceManager.GetString("___It_is_fairly_warm_at_the_south_pole___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is freezing in Kriva..
        /// </summary>
        internal static string ___It_is_freezing_in_Kriva___ {
            get {
                return ResourceManager.GetString("___It_is_freezing_in_Kriva___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is freezing in Verl..
        /// </summary>
        internal static string ___It_is_freezing_in_Verl___ {
            get {
                return ResourceManager.GetString("___It_is_freezing_in_Verl___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not freezing in Kriva..
        /// </summary>
        internal static string ___It_is_not_freezing_in_Kriva___ {
            get {
                return ResourceManager.GetString("___It_is_not_freezing_in_Kriva___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not freezing in Verl..
        /// </summary>
        internal static string ___It_is_not_freezing_in_Verl___ {
            get {
                return ResourceManager.GetString("___It_is_not_freezing_in_Verl___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriva, Slovakia.
        /// </summary>
        internal static string ___Kriva__Slovakia__ {
            get {
                return ResourceManager.GetString("___Kriva__Slovakia__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriva station is not available..
        /// </summary>
        internal static string ___Kriva_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___Kriva_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LREAL From PLC.
        /// </summary>
        internal static string ___LREAL_From_PLC__ {
            get {
                return ResourceManager.GetString("___LREAL_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North pole station.
        /// </summary>
        internal static string ___North_pole_station__ {
            get {
                return ResourceManager.GetString("___North_pole_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North pole station is not available..
        /// </summary>
        internal static string ___North_pole_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___North_pole_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string ___Pressure__ {
            get {
                return ResourceManager.GetString("___Pressure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL From PLC.
        /// </summary>
        internal static string ___REAL_From_PLC__ {
            get {
                return ResourceManager.GetString("___REAL_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, the weather situation is following.
        /// </summary>
        internal static string ___So__the_weather_situation_is_following__ {
            get {
                return ResourceManager.GetString("___So__the_weather_situation_is_following__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South pole station.
        /// </summary>
        internal static string ___South_pole_station__ {
            get {
                return ResourceManager.GetString("___South_pole_station__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South pole station is not available..
        /// </summary>
        internal static string ___South_pole_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___South_pole_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station name (ICAO).
        /// </summary>
        internal static string ___Station_name__ICAO___ {
            get {
                return ResourceManager.GetString("___Station_name__ICAO___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station status.
        /// </summary>
        internal static string ___Station_status__ {
            get {
                return ResourceManager.GetString("___Station_status__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String From PLC.
        /// </summary>
        internal static string ___String_From_PLC__ {
            get {
                return ResourceManager.GetString("___String_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String unknown From PLC.
        /// </summary>
        internal static string ___String_unknown_From_PLC__ {
            get {
                return ResourceManager.GetString("___String_unknown_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string ___Temperature__ {
            get {
                return ResourceManager.GetString("___Temperature__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME_OF_DAY From PLC.
        /// </summary>
        internal static string ___TIME_OF_DAY_From_PLC__ {
            get {
                return ResourceManager.GetString("___TIME_OF_DAY_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInteger From PLC.
        /// </summary>
        internal static string ___UInteger_From_PLC__ {
            get {
                return ResourceManager.GetString("___UInteger_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verl, Germany.
        /// </summary>
        internal static string ___Verl__Germany__ {
            get {
                return ResourceManager.GetString("___Verl__Germany__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verl station is not available..
        /// </summary>
        internal static string ___Verl_station_is_not_available___ {
            get {
                return ResourceManager.GetString("___Verl_station_is_not_available___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string ___Visibility__ {
            get {
                return ResourceManager.GetString("___Visibility__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What plc says.
        /// </summary>
        internal static string ___What_plc_says__ {
            get {
                return ResourceManager.GetString("___What_plc_says__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind heading.
        /// </summary>
        internal static string ___Wind_heading__ {
            get {
                return ResourceManager.GetString("___Wind_heading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        internal static string ___Wind_speed__ {
            get {
                return ResourceManager.GetString("___Wind_speed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD From PLC.
        /// </summary>
        internal static string ___WORD_From_PLC__ {
            get {
                return ResourceManager.GetString("___WORD_From_PLC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string ___World__ {
            get {
                return ResourceManager.GetString("___World__", resourceCulture);
            }
        }
    }
}
