CLASS full_of_primitives_match
    VAR PUBLIC
       
        myBOOL	            : BOOL;
        myBYTE	            : BOOL;
        myWORD	            : BOOL;
        myDWORD	        : BOOL;
        myLWORD	        : BOOL;
        mySINT	            : BOOL;
        myINT	            : BOOL;
        myDINT	            : BOOL;
        myLINT	            : BOOL;
        myUSINT	        : BOOL;
        myUINT	            : BOOL;
        myUDINT	        : BOOL;
        myULINT	        : BOOL;
        myREAL	            : BOOL;
        myLREAL	        : BOOL;
        myTIME	            : BOOL;
        myLTIME	        : BOOL;
        myDATE	            : BOOL;
        myLDATE	        : BOOL;
        myTIME_OF_DAY	    : BOOL;
        myLTIME_OF_DAY	    : BOOL;
        myDATE_AND_TIME    : BOOL;
        myLDATE_AND_TIME   : BOOL;
        // myCHAR	            : BOOL;
        // myWCHAR	        : BOOL;
        mySTRING	        : BOOL;
        myWSTRING	        : BOOL;
    END_VAR    
END_CLASS