CLASS hierarchy_2
    VAR PUBLIC
        item_member_property_1   :     hierarchy_0;
        item_member_property_2   :     hierarchy_0;
        item_member_property_3   :     hierarchy_0;
        item_member_property_4   :     hierarchy_0;
        item_member_property_5   :     hierarchy_0;
        item_member_property_6   :     hierarchy_0;
        item_member_property_7   :     hierarchy_0;
        item_member_property_8   :     hierarchy_0;
        item_member_property_9   :     hierarchy_0;
        item_member_property_10  :     hierarchy_0;
        item_member_property_12  :     hierarchy_0;
        item_member_property_13  :     hierarchy_0;
        item_member_property_14  :     hierarchy_0;
        item_member_property_15  :     hierarchy_0;
        item_member_property_16  :     hierarchy_0;
        item_member_property_17  :     hierarchy_0;
        item_member_property_18  :     hierarchy_0;
        item_member_property_19  :     hierarchy_0;
    END_VAR    
END_CLASS