{S7.extern=ReadWrite}
CLASS hierarchy_6
    VAR PUBLIC
        item_member_property_1  :      hierarchy_4;
        item_member_property_2  :      hierarchy_4;
        item_member_property_3  :      hierarchy_4;
        item_member_property_4  :      hierarchy_4;
        item_member_property_5  :      hierarchy_4;
        item_member_property_6  :      hierarchy_4;
        item_member_property_7   :     hierarchy_4;
        item_member_property_8  :      hierarchy_4;
        item_member_property_9  :      hierarchy_4;
        item_member_property_10  :     hierarchy_4;
        item_member_property_12  :     hierarchy_4;
        item_member_property_13  :     hierarchy_4;
        item_member_property_14  :     hierarchy_4;
        item_member_property_15  :     hierarchy_4;
        item_member_property_16  :     hierarchy_4;
        item_member_property_17  :     hierarchy_4;
        item_member_property_18  :     hierarchy_4;
        item_member_property_19  :     hierarchy_4;
    END_VAR    
END_CLASS