CLASS hierarchy_0
    VAR PUBLIC
        item_member_property_1   :     full_of_primitives;
        item_member_property_2   :     full_of_primitives;
        item_member_property_3   :     full_of_primitives;
        item_member_property_4   :     full_of_primitives;
        item_member_property_5   :     full_of_primitives;
        item_member_property_6   :     full_of_primitives;
        item_member_property_7   :     full_of_primitives;
        item_member_property_8   :     full_of_primitives;
        item_member_property_9   :     full_of_primitives;
        item_member_property_10  :     full_of_primitives;
        item_member_property_12  :     full_of_primitives;
        item_member_property_13  :     full_of_primitives;
        item_member_property_14  :     full_of_primitives;
        item_member_property_15  :     full_of_primitives;
        item_member_property_16  :     full_of_primitives;
        item_member_property_17  :     full_of_primitives;
        item_member_property_18  :     full_of_primitives;
        item_member_property_19  :     full_of_primitives;
    END_VAR    
END_CLASS