USING FileWithUsingsSimpleFirstLevelNamespace;
USING FileWithUsingsSimpleQualifiedNamespace.Qualified;
USING FileWithUsingsHelloLevelOne.FileWithUsingsHelloLevelTwo;

NAMESPACE FileWithUsingsSimpleFirstLevelNamespace
    
END_NAMESPACE

NAMESPACE FileWithUsingsSimpleQualifiedNamespace.Qualified
    
END_NAMESPACE

NAMESPACE FileWithUsingsHelloLevelOne
    NAMESPACE FileWithUsingsHelloLevelTwo
    END_NAMESPACE    
END_NAMESPACE    