name: pr-dev

on:  
  pull_request:
    branches: [ "dev" ]
    paths:
     - 'src/**'
     - 'cake/**'
     - '.github/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: [self-hosted, Windows, X64, L2]  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'   
                   
    - name: "Build  script"  
      run: dotnet build cake/Build.csproj
                       
    - name: "Run build script"
      run: dotnet run --project cake/Build.csproj --do-test true --do-pack true --test-level 1      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test report
        path: 'TestResults/*.xml'   
        reporter: dotnet-trx
